server:
  port: 8081
  servlet:
    context-path: /bx-gis

spring:
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .html
#      #设定静态文件路径，js,css等
#    static-path-pattern: /js/**
  profiles:
    active: test
  #thymeleaf start 模板引擎
  thymeleaf:
    # spring.thymeleaf.mode的默认值是HTML5，其实是一个很严格的检查，改为LEGACYHTML5可以得到一个可能更友好亲切的格式要求。
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    #开发时关闭缓存,不然没法看到实时页面
    cache: true
    prefix: classpath:/templates/
    suffix: .html
  #thymeleaf end

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.bx.gis.entity


